FROM docker.io/debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive
ENV PATH="/opt/TinyTeX/bin/x86_64-linux:${PATH}"

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        fontconfig \
        ghostscript \
        make \
        perl \
        wget \
        xz-utils \
    && rm -rf /var/lib/apt/lists/*

RUN set -eux; \
    mkdir -p /tmp/install-tl; \
    wget -qO /tmp/install-tl-unx.tar.gz https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/tlnet/install-tl-unx.tar.gz; \
    tar -xzf /tmp/install-tl-unx.tar.gz -C /tmp/install-tl --strip-components=1; \
    printf '%s\n' \
        'selected_scheme scheme-infraonly' \
        'TEXDIR /opt/TinyTeX' \
        'TEXMFLOCAL /opt/TinyTeX/texmf-local' \
        'TEXMFSYSVAR /opt/TinyTeX/texmf-var' \
        'TEXMFSYSCONFIG /opt/TinyTeX/texmf-config' \
        'TEXMFVAR ~/.texlive/texmf-var' \
        'TEXMFCONFIG ~/.texlive/texmf-config' \
        'TEXMFHOME ~/texmf' \
        'binary_x86_64-linux 1' \
        'option_doc 0' \
        'option_src 0' \
        'tlpdbopt_install_docfiles 0' \
        'tlpdbopt_install_srcfiles 0' \
        > /tmp/texlive.profile; \
    /tmp/install-tl/install-tl -profile /tmp/texlive.profile -repository https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/tlnet; \
    rm -rf /tmp/install-tl /tmp/install-tl-unx.tar.gz /tmp/texlive.profile; \
    tlmgr option repository https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/texlive/tlnet; \
    tlmgr option docfiles 0; \
    tlmgr option srcfiles 0; \
    tlmgr install \
        amsfonts \
        amsmath \
        algorithms \
        bibtex \
        booktabs \
        caption \
        ctex \
        fancyhdr \
        fontspec \
        gbt7714 \
        geometry \
        graphics \
        hyperref \
        latex \
        latex-bin \
        latexmk \
        listings \
        multirow \
        overpic \
        pgf \
        pgfplots \
        soul \
        titlesec \
        tocloft \
        tools \
        xcolor \
        xecjk \
        xetex \
        zhnumber \
    ; \
    tlmgr path add; \
    fmtutil-sys --all

RUN tlmgr install float eepic

WORKDIR /work

CMD ["latexmk", "-xelatex", "-synctex=1", "-interaction=nonstopmode", "-halt-on-error", "-file-line-error", "-outdir=build", "main.tex"]
